### ISSUE TITLE
Rework xr_combat_ignore

### ISSUE THREAD

**Issue by DimasDSF** [DimasDSF/VipersStalkerCoPMod#64]
### Current issues:

- Combat ignore scheme requires a rework

- - Stalkers get agressive at huge distances
- -  During surge stalkers leave covers to fight and die #63 (Stop stalkers leaving surge covers to kill enemies outside of surge cover)
- -  During surge stalkers ignore imminent death and go straight into deadly cqc enemies

---------

### Solution:

1. Stalkers should ignore long range enemies unless they had an established contact with them
2. Stalkers should ignore long range mutants if stalkers are in a surge cover and mutants are not close enough
3. Stalkers surge combat ignore range should be conditional:
     - The closer to the final wave the smaller
     - constant(small) until they reach cover then conditional (1.)
     - enemy class conditional
4. Weather conditions should affect stalkers range of detection
     - Fog
     - Rain
5. Day/Night

_xr_combat_ignore.script_

--------

- [x] Gather a database of day/night cycle screenshots after completing #65 (Rework Weather)

--------

### ToDo:

- [x] Surge timer range checks
- [x] Day/Night checks
- [ ] Logical checks

--------
### Update:

- Set minimum range to be 15m=sqrt(225)

--------
#16 (Balance the NPC Detection radius) is now considered a parallel development issue

**Comment by DimasDSF** [comment]
-Added a range check function checking for if the enemy is in range
depending on if it is day/night time, if the NPC is in danger mode or in
free mode, if the surge is running

**Comment by DimasDSF** [comment]
May be reopened to add a table driven enemy list and enemy mutant distinction conditions
